### ISSUE TITLE
Trying to execute code from example and ge an error

### ISSUE THREAD

**Issue by burley1** [BayatGames/JsonFormatter#2]
TargetParameterCountException: parameters do not match signature
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:188)
System.Reflection.MonoProperty.GetValue (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] index, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoProperty.cs:297)
BayatGames.Serialization.Formatters.Json.JsonTextWriter.WriteObject (System.Object value, System.Type type) (at Assets/BayatGames/JsonFormatter/Scripts/JsonTextWriter.cs:218)
BayatGames.Serialization.Formatters.Json.JsonTextWriter.Write (System.Object value) (at Assets/BayatGames/JsonFormatter/Scripts/JsonTextWriter.cs:93)
BayatGames.Serialization.Formatters.Json.JsonFormatter.Serialize (System.IO.TextWriter output, System.Object value) (at Assets/BayatGames/JsonFormatter/Scripts/JsonFormatter.cs:121)
BayatGames.Serialization.Formatters.Json.JsonFormatter.Serialize (System.Object value) (at Assets/BayatGames/JsonFormatter/Scripts/JsonFormatter.cs:98)
BayatGames.Serialization.Formatters.Json.JsonFormatter.SerializeObject (System.Object value) (at Assets/BayatGames/JsonFormatter/Scripts/JsonFormatter.cs:196)
Assets.Editor.DefaultObjects.Save () (at Assets/Editor/DefaultObjects.cs:108)
Assets.Editor.DefaultObjects.OnGUI () (at Assets/Editor/DefaultObjects.cs:62)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:295)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:288)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:255)

**Comment by hasanbayatme** [comment]
Hi, try to use the latest version, then let me know if you had this error again.
Use the latest release on this repository not Asset Store.

Thanks.

**Comment by burley1** [comment]
Seems it works. But it will be very useful if there will no different versions available in different sources.
Thanks.

**Comment by hasanbayatme** [comment]
Yes, it is just a new update, that I will submit for review on Asset Store, it is the first time it is happened and would be the last.
